import Head from 'next/head'
import Image from 'next/image'
import { Layout } from '@/components/Layout/Layout'
import { Header } from '@/components/Header/Header'
import { Content } from '@/components/Content/Content'
import { CardList } from '@/components/CardList/CardList'
import { GetServerSideProps, GetServerSidePropsContext, NextPage } from 'next'
import axios from 'axios'
import { useAppSelector } from '@/components/Hooks/useApp'
import { getCookie } from 'cookies-next'
import { ICardProps } from '@/components/CardList/Card/Card'
import { getOptimizatedData } from '@/utils/getOptimizatedData'
import { Modal } from '@/components/ui-components/Modal/Modal'
import { useRouter } from 'next/router'
import { PostInfoCard } from '@/components/PostInfoCard/PostInfoCard'
import { SubredditInfoCard } from '@/components/SubredditInfoCard/SubredditInfoCard'

const props = ['id', 'title', 'thumbnail', 'permalink', 'author', 'score', 'num_comments', 'created', 'media']

export const getServerSideProps: GetServerSideProps = async ({ req, res }: GetServerSidePropsContext) => {
  const token = getCookie('token', { req, res })
  console.log(token)

  if (!token) return {
    props: {postsData: []},
    // redirect: {
    //   destination: '/auth',
    //   permanent: false,
    // },
  };
  const {data} = await axios.get('https://oauth.reddit.com/r/all/hot.json?sr_detail=true', {
    headers: { Authorization: `bearer ${token}` },
    params: {
      // limit: 10,
      // after: afterNext,
    }
  })
  const postsData = data.data.children.map((item: { data: any }) => item.data)
  console.log(postsData)
  const optimizatedData = getOptimizatedData(postsData, props)

  return {
    props: {postsData: optimizatedData, data: postsData},
  }
}

// interface IPost {
//   data: ICardProps;
// }

export interface IHomePageProps {
  postsData: ICardProps[];
  data: any[]
}


const HomePage: NextPage<IHomePageProps> = ({postsData, data}) => {
  return (
    <>
      <Head>
        <title>Reddit-mirror</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Header />
        <Content>
          <CardList postsData={postsData}/>
        </Content>
      </Layout>
    </>
  )
}


export default HomePage
